### ISSUE TITLE
Error: Backend wasn't recognised

### ISSUE THREAD

**Issue by busla** [yetty/django-embed-video#48]
I got the following error when loading a page with embed-video code but found the solution so I´ll post the traceback and my template code.

I´m using Swiper (https://github.com/nolimits4web/Swiper/) as a carousel with links on each slide to Vimeo videos and html5lightbox (http://html5box.com/html5lightbox/) to display the the embeded video. 

I needed to include the html5lightbox.js file at the very end of my javascript includes to get rid of the error.

{% load embed_video_tags %}  
     
    <div class="testimonial">      
      <div class="avatar-testimonial">
        <img src="{{MEDIA_URL}}{{testimonial.avatar.image.name}}">
      </div>
      <p class="client">{{ testimonial.title }}</p>
      <p class="info">{{ testimonial.work_title }}</p>
      <hr class="short" />
      <p class="quote">{{ testimonial.body|safe|truncatewords:10 }}</p>
        {% video testimonial.video as testimonial_video%}
            <a href="{{testimonial_video.url}}" class="html5lightbox btn btn-watch" role="button"><span class="fa fa-play"></span> WATCH VIDEO</a>
        {% endvideo %}       
    </div>
 

```
Backend wasn't recognised (``)
Traceback (most recent call last):
  File "/Users/nonni/venv/p3-d17/lib/python3.4/site-packages/embed_video/templatetags/embed_video_tags.py", line 115, in render
    return self.__render_block(url, context, resolved_query)
  File "/Users/nonni/venv/p3-d17/lib/python3.4/site-packages/embed_video/templatetags/embed_video_tags.py", line 134, in __render_block
    context[as_var] = self.get_backend(url, context=context, query=query)
  File "/Users/nonni/venv/p3-d17/lib/python3.4/site-packages/embed_video/templatetags/embed_video_tags.py", line 150, in get_backend
    else detect_backend(str(backend_or_url))
  File "/Users/nonni/venv/p3-d17/lib/python3.4/site-packages/embed_video/backends.py", line 59, in detect_backend
    raise UnknownBackendException
embed_video.backends.UnknownBackendException
Backend wasn't recognised (``)
Traceback (most recent call last):
  File "/Users/nonni/venv/p3-d17/lib/python3.4/site-packages/embed_video/templatetags/embed_video_tags.py", line 115, in render
    return self.__render_block(url, context, resolved_query)
  File "/Users/nonni/venv/p3-d17/lib/python3.4/site-packages/embed_video/templatetags/embed_video_tags.py", line 134, in __render_block
    context[as_var] = self.get_backend(url, context=context, query=query)
  File "/Users/nonni/venv/p3-d17/lib/python3.4/site-packages/embed_video/templatetags/embed_video_tags.py", line 150, in get_backend
    else detect_backend(str(backend_or_url))
  File "/Users/nonni/venv/p3-d17/lib/python3.4/site-packages/embed_video/backends.py", line 59, in detect_backend
    raise UnknownBackendException
embed_video.backends.UnknownBackendException
Backend wasn't recognised (``)
Traceback (most recent call last):
  File "/Users/nonni/venv/p3-d17/lib/python3.4/site-packages/embed_video/templatetags/embed_video_tags.py", line 115, in render
    return self.__render_block(url, context, resolved_query)
  File "/Users/nonni/venv/p3-d17/lib/python3.4/site-packages/embed_video/templatetags/embed_video_tags.py", line 134, in __render_block
    context[as_var] = self.get_backend(url, context=context, query=query)
  File "/Users/nonni/venv/p3-d17/lib/python3.4/site-packages/embed_video/templatetags/embed_video_tags.py", line 150, in get_backend
    else detect_backend(str(backend_or_url))
  File "/Users/nonni/venv/p3-d17/lib/python3.4/site-packages/embed_video/backends.py", line 59, in detect_backend
    raise UnknownBackendException
embed_video.backends.UnknownBackendException
[12/Feb/2015 12:25:53] "GET /testimonials/ HTTP/1.1" 200 10943
[12/Feb/2015 12:25:53] "GET /static/promo/css/style.css HTTP/1.1" 304 0
Backend wasn't recognised (``)
Traceback (most recent call last):
  File "/Users/nonni/venv/p3-d17/lib/python3.4/site-packages/embed_video/templatetags/embed_video_tags.py", line 115, in render
    return self.__render_block(url, context, resolved_query)
  File "/Users/nonni/venv/p3-d17/lib/python3.4/site-packages/embed_video/templatetags/embed_video_tags.py", line 134, in __render_block
    context[as_var] = self.get_backend(url, context=context, query=query)
  File "/Users/nonni/venv/p3-d17/lib/python3.4/site-packages/embed_video/templatetags/embed_video_tags.py", line 150, in get_backend
    else detect_backend(str(backend_or_url))
  File "/Users/nonni/venv/p3-d17/lib/python3.4/site-packages/embed_video/backends.py", line 59, in detect_backend
    raise UnknownBackendException
embed_video.backends.UnknownBackendException
Backend wasn't recognised (``)
Traceback (most recent call last):
  File "/Users/nonni/venv/p3-d17/lib/python3.4/site-packages/embed_video/templatetags/embed_video_tags.py", line 115, in render
    return self.__render_block(url, context, resolved_query)
  File "/Users/nonni/venv/p3-d17/lib/python3.4/site-packages/embed_video/templatetags/embed_video_tags.py", line 134, in __render_block
    context[as_var] = self.get_backend(url, context=context, query=query)
  File "/Users/nonni/venv/p3-d17/lib/python3.4/site-packages/embed_video/templatetags/embed_video_tags.py", line 150, in get_backend
    else detect_backend(str(backend_or_url))
  File "/Users/nonni/venv/p3-d17/lib/python3.4/site-packages/embed_video/backends.py", line 59, in detect_backend
    raise UnknownBackendException
embed_video.backends.UnknownBackendException
Backend wasn't recognised (``)
Traceback (most recent call last):
  File "/Users/nonni/venv/p3-d17/lib/python3.4/site-packages/embed_video/templatetags/embed_video_tags.py", line 115, in render
    return self.__render_block(url, context, resolved_query)
  File "/Users/nonni/venv/p3-d17/lib/python3.4/site-packages/embed_video/templatetags/embed_video_tags.py", line 134, in __render_block
    context[as_var] = self.get_backend(url, context=context, query=query)
  File "/Users/nonni/venv/p3-d17/lib/python3.4/site-packages/embed_video/templatetags/embed_video_tags.py", line 150, in get_backend
    else detect_backend(str(backend_or_url))
  File "/Users/nonni/venv/p3-d17/lib/python3.4/site-packages/embed_video/backends.py", line 59, in detect_backend
    raise UnknownBackendException
embed_video.backends.UnknownBackendException
```

**Comment by yetty** [comment]
Obviously the variable `testimonial.video` contains emty string. In this case backend cannot be recognized and it is corrert behaviour. This exception is catched in `embed_video_tags.py:103` and just logged as exception - check, how your logging is configured, you may see this exception in console, I suppose. The page should be rendered normally.

**Comment by yetty** [comment]
No response for long time. Closing.

**Comment by SalahAdDin** [comment]
So bad.

**Comment by MicroWriting** [comment]
Hello, I have the same problem.
I am making small web service using almost same environment and code.
I checked the console, error message displayed as follows.

`Uncaught TypeError: Cannot read property 'fn' of undefined
    at util.js:68
    at util.js:10
    at bootstrap.min.js:6
    at bootstrap.min.js:6`

**Comment by SalahAdDin** [comment]
I think you have to make a new issue.

**Comment by MicroWriting** [comment]
OK. I already made new issue as follows.
https://github.com/jazzband/django-embed-video/issues/85

**Comment by reyesvicente** [comment]
What's this fix on this?

**Comment by aleksihakli** [comment]
I believe the example may be outdated please use #85 for discussion.
